Rename bootstrap-machine to bootstrap-machine-osx.

diff --git a/bootstrap-machine-osx b/bootstrap-machine-osx
--- a/bootstrap-machine-osx
+++ b/bootstrap-machine-osx
@@ -1,5 +1,21 @@
 #!/usr/bin/env bash
 
+BLACK=30
+RED=31
+GREEN=32
+YELLOW=33
+BLUE=34
+MAGENTA=35
+CYAN=36
+LIGHT_GREY=37
+DARK_GREY=90
+LIGHT_RED=91
+LIGHT_GREEN=92
+LIGHT_YELLOW=93
+LIGHT_BLUE=94
+LIGHT_MAGENTA=95
+LIGHT_CYAN=96
+
 # Ask for the administrator password upfront
 sudo -v
 
@@ -9,42 +25,129 @@ else
   brew update
 fi
 
-brew install git
-brew install tmux
-brew install vim
-brew install wget
+say() {
+  if [ ! -z $2 ]; then
+    COLOR=$2
+  else
+    COLOR=0
+  fi
 
-brew install caskroom/cask/brew-cask
+  echo -e "\033["$COLOR"m$1\033[0m"
+}
 
-brew cask install forklift
-brew cask install dropbox
-brew cask install google-chrome
-brew cask install iterm2
-brew cask install kaleidoscope
-brew cask install navicat-premium
-brew cask install sublime-text
-brew cask install tower
-brew cask install tunnelblick
-brew cask install tower
-brew cask install textexpander
-brew cask install vmware-fusion
+say_dim() {
+  echo -e "\033[2m$1\033[0m"
+}
+
+announce() {
+  if [ ! -z $2 ]; then
+    COLOR=$2
+  else
+    COLOR=0
+  fi
+
+  echo -en "\033["$COLOR"m$1 ...\033[0m"
+}
+
+perform() {
+  command=$1
+  output=`$command 2>&1`
+  result=$?
+  if [[ $result -eq 0 ]]; then
+    echo -e "\033[32mOK\033[0m"
+  else
+    echo -e "\033[31mERROR\033[0m"
+    echo -e "$output" >&2
+    exit $result
+  fi
+}
+
+brew_expand_alias() {
+  brew info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
+}
+
+install_brew() {
+  if brew_is_installed "$1"; then
+    say "$1 brew already installed"
+  else
+    announce "Installing brew $1"
+    perform "brew install $1"
+  fi
+}
+
+install_cask() {
+  if cask_is_installed "$1"; then
+    say "$1 cask already installed"
+  else
+    announce "Installing cask $1" $CYAN
+    perform "brew cask install $1"
+  fi
+}
+
+brew_is_installed() {
+  local name="$(brew_expand_alias "$1")"
+
+  brew list -1 | grep -Fqx "$name"
+}
+
+cask_is_installed() {
+  brew cask list -1 | grep -Fqx "$1"
+}
+
+brew_is_upgradable() {
+  local name="$(brew_expand_alias "$1")"
+
+  brew outdated --quiet "$name" >/dev/null
+  [[ $? -ne 0 ]]
+}
+
+install_brew 'ctags'
+install_brew 'dnsmasq'
+install_brew 'git'
+install_brew 'git-crypt'
+install_brew 'tmux'
+install_brew 'vim'
+install_brew 'wget'
+
+install_brew 'caskroom/cask/brew-cask'
+
+install_cask 'alfred'
+install_cask 'dropbox'
+install_cask 'evernote'
+install_cask 'forklift'
+install_cask 'google-chrome'
+install_cask 'iterm2'
+install_cask 'kaleidoscope'
+install_cask 'navicat-premium'
+install_cask 'sublime-text'
+install_cask 'tower'
+install_cask 'tunnelblick'
+install_cask 'tower'
+install_cask 'textexpander'
+install_cask 'vmware-fusion'
 
 ZSH_DIRECTORY=~/.oh-my-zsh
 if [ ! -d "$ZSH_DIRECTORY" ]; then
   git clone git@github.com:midas/oh-my-zsh.git $ZSH_DIRECTORY
   cd $ZSH_DIRECTORY
   git checkout jason
-  chsh -s /bin/zsh
+fi
+
+if [[ "$SHELL" != */zsh ]]; then
+  say "Changing shell to zsh"
+  chsh -s $(which zsh)
 fi
 
 DOTFILES_DIRECTORY=~/.dotfiles
 if [ ! -d "$DOTFILES_DIRECTORY" ]; then
+  say "dotfiles already installed"
   git clone git@github.com:midas/dotfiles.git ~/.dotfiles
   ~/.dotfiles/bootstrap
 fi
 
 NEOBUNDLE_DIRECTORY=~/.vim/bundle/neobundle.vim
 if [ ! -d "$NEOBUNDLE_DIRECTORY" ]; then
+  say "Neobundle already installed"
   mkdir -p ~/.vim/bundle
   git clone https://github.com/Shougo/neobundle.vim $NEOBUNDLE_DIRECTORY
 fi
@@ -52,12 +155,21 @@ fi
 # Install RVM
 rvm --version > /dev/null
 if [ $? != 0 ]; then
+  say "RVM already installed"
   brew install gpg2 # for RVM
   gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
   \curl -sSL https://get.rvm.io | bash -s stable
 fi
 
-open ~/.dotfiles/powerline-fonts/Monaco+for+Powerline.otf
+say "Configuring Bundler for faster, parallel gem installation ..."
+number_of_cores=$(sysctl -n hw.ncpu)
+bundle config --global jobs $((number_of_cores - 1))
+
+if [ ! -f ~/Library/Fonts/Monaco+for+Powerline.otf ]; then
+  open ~/.dotfiles/powerline-fonts/Monaco+for+Powerline.otf
+else
+  say "Monaco+for+Powerline.otf already installed"
+fi
 
 # Set sidebar icon size to medium
 defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2
